# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone X",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE"
])

languages([
  "en-US"
])

# Make sure we start fresh so we don't have lingering data saved
reinstall_app true

# The name of the scheme which contains the UI Tests
scheme "findmybusnj"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

ios_version '11.1'

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
